// Generated by ts-migrate. Properties the code hangs off window and globalThis,
// declared once here so every read and write of them type-checks instead
// of needing a cast at each site. Narrow a type to the real shape when you
// know it and ts-migrate keeps your version. Delete an entry once
// something else declares the property. Do not add entries by hand: the
// file is rewritten from its own declarations on every run.
export {};

declare global {
  interface Window {
    guardian: any;
  }
}
