// Generated by ts-migrate. Modules whose packages ship no type definitions, declared
// here so their imports are `any` instead of an error at every import site.
// Install the types when a package has them and delete its line; ts-migrate
// drops entries whose types it can resolve the next time it runs.
declare module 'react-datepicker';
