# NO SECRETS (ie credentials) SHOULD GO IN THIS FILE
#
# The secrets file is stored in S3 - it's called 'media-atom-maker.private.conf' and will pull in the
# correct "[STAGE].public.conf" file with an include.

stage="CODE"
# Sentry DSN for frontend/backend error reporting in CODE
raven.url="https://ad10e2c312e949a7a6c0421ec704287e@o14302.ingest.us.sentry.io/129691"
# Enable guarded debug exception routes in CODE
FAULT_INJECTION_ENABLED=true