#!/usr/bin/env bash

if [ $# -ne 7 ]
then
  echo "usage: $0 <STACK_NAME> <AWS_PROFILE> <PANDA_AWS_PROFILE> <DOMAIN> <YOUTUBE_CLIENT_ID> <YOUTUBE_CLIENT_SECRET> <YOUTUBE_REFRESH_TOKEN>"
  exit 1
fi

STACK_NAME=$1
AWS_PROFILE=$2
PANDA_AWS_PROFILE=$3
DOMAIN=$4
YOUTUBE_CLIENT_ID=$5
YOUTUBE_CLIENT_SECRET=$6
YOUTUBE_REFRESH_TOKEN=$7

function get_resource() {
    aws cloudformation describe-stack-resources \
        --stack-name ${STACK_NAME} \
        --profile ${AWS_PROFILE} \
        | jq ".StackResources[] | select(.LogicalResourceId == \"$1\") | .PhysicalResourceId" | tr -d '"'
}

LIVE_STREAM_NAME=$(get_resource "MediaAtomLiveKinesisStream")
PREVIEW_STREAM_NAME=$(get_resource "MediaAtomPreviewKinesisStream")

PREVIEW_REINDEX_STREAM_NAME=${PREVIEW_STREAM_NAME}
PUBLISHED_REINDEX_STREAM_NAME=${LIVE_STREAM_NAME}

DYNAMO_TABLE=$(get_resource "MediaAtomsDynamoTable")
DYNAMO_PUBLISHED_TABLE=$(get_resource "PublishedMediaAtomsDynamoTable")

sed -e "s/{DOMAIN}/${DOMAIN}/g" \
    -e "s/{PANDA_PROFILE}/${PANDA_AWS_PROFILE}/g" \
    -e "s/{AWS_PROFILE}/${AWS_PROFILE}/g" \
    -e "s/{LIVE_STREAM_NAME}/${LIVE_STREAM_NAME}/g" \
    -e "s/{PREVIEW_STREAM_NAME}/${PREVIEW_STREAM_NAME}/g" \
    -e "s/{PREVIEW_REINDEX_STREAM_NAME}/${PREVIEW_REINDEX_STREAM_NAME}/g" \
    -e "s/{PUBLISHED_REINDEX_STREAM_NAME}/${PUBLISHED_REINDEX_STREAM_NAME}/g" \
    -e "s/{DYNAMO_TABLE}/${DYNAMO_TABLE}/g" \
    -e "s/{DYNAMO_PUBLISHED_TABLE}/${DYNAMO_PUBLISHED_TABLE}/g" \
    -e "s/{YT_CLIENT_ID}/${YOUTUBE_CLIENT_ID}/g" \
    -e "s/{YT_CLIENT_SECRET}/${YOUTUBE_CLIENT_SECRET}/g" \
    -e "s/{YT_REFRESH_TOKEN}/${YOUTUBE_REFRESH_TOKEN}/g" \
    ../conf/reference.conf > ../conf/application.conf
