AWSTemplateFormatVersion: "2010-09-09"
Description: "A pipeline for uploading video to YouTube or an S3 bucket"

# This template is separate from the main one and is managed as a sub-deployment in riff-raff.yaml.
# The main app looks up the resources by STAGE relying on the naming convention.

Parameters:
  BuildBucket:
    Description: "The S3 bucket where builds live"
    Type: "String"
  ConfigBucket:
    Description: "The S3 bucket where configuration lives"
    Type: "String"
  App:
    Description: "App name"
    Type: "String"
    Default: "media-atom-pipeline"
  Stack:
    Description: "Stack name"
    Type: "String"
    Default: "media-service"
  Stage:
    Description: "Stage name"
    Type: "String"
    Default: "DEV"
  UploadBucketName:
    Description: "The S3 bucket where videos are uploaded to"
    Type: "String"
  DestinationBucketName:
    Description: "The S3 bucket where transcoded videos are stored"
    Type: "String"
  MediaAtomTable:
    Description: "The Dynamo table where preview media atoms are stored"
    Type: "String"
  ContentAtomArn:
    Description: "ARN of the cross account role to access the content atom kinesis stream"
    Type: "String"
  ManualPlutoTable:
    Description: "The Dynamo table to store videos that must be manually synced with Pluto"
    Type: "String"
  NotificationEmailFrom:
    Description: "email address where notifications of missing pluto ids are sent from"
    Type: "String"
    Default: "digitalcms.dev@guardian.co.uk"
  AlertWebhook:
    Description: "Where CloudWatch alerts are sent"
    Type: "String"
  PlutoSendbackStreamName:
    Description: Name (not ARN) of the Kinesis stream which passes messages back to Pluto
    Type: String
  PlutoSendbackStreamKmsKey:
    Description: ARN of the KMS key used to encrypt messages sent to pluto
    Type: String
  IconikNotificationSQSQueueArn:
    Description: "ARN of the SQS queue to send Iconik notifications to"
    Type: "String"

Conditions:
  CreateProdResources: !Equals [!Ref "Stage", "PROD"]
  CreateCodeResources: !Equals [!Ref "Stage", "CODE"]
  CreateDevResources:  !Equals [!Ref "Stage", "DEV"]

Resources:
  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "LambdaExecutionPolicy"
          PolicyDocument:
            Statement:
              - Effect: "Allow"
                Action: ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"]
                Resource: "*"
              - Effect: "Allow"
                Action: ["s3:GetObject"]
                Resource: !Sub ["arn:aws:s3:::${Bucket}/*", { "Bucket": !Ref ConfigBucket }]
              - Effect: "Allow"
                Action: ["s3:*"]
                Resource:
                  - !Sub ["arn:aws:s3:::${Bucket}", { "Bucket": !Ref UploadBucketName }]
                  - !Sub ["arn:aws:s3:::${Bucket}/*", { "Bucket": !Ref UploadBucketName }]
              - Effect: "Allow"
                Action: ["dynamodb:*"]
                Resource:
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${MediaAtomTable}"
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ManualPlutoTable}"
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${App}-cache-${Stage}"
              - Effect: "Allow"
                Action: ["elastictranscoder:CreateJob", "elastictranscoder:ReadJob"]
                Resource: "arn:aws:elastictranscoder:*"
              - Effect: "Allow"
                Action: [ "mediaconvert:CreateJob", "mediaconvert:GetJob" ]
                Resource: "*"
              - Effect: "Allow"
                Action: [ "iam:PassRole" ]
                Resource: !GetAtt [ MediaConvertRole, Arn ]
              - Effect: Allow
                Action:
                - ses:SendEmail
                Resource: '*'
                Condition:
                  StringEquals:
                    ses:FromAddress: !Ref 'NotificationEmailFrom'
        - PolicyName: LambdaKinesisAccessPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - kinesis:PutRecord
                  - kinesis:PutRecords
                Resource:
                  - !Sub "arn:aws:kinesis:${AWS::Region}:${AWS::AccountId}:stream/${PlutoSendbackStreamName}"
              - Effect: Allow
                Action: kms:GenerateDataKey
                Resource: !Ref PlutoSendbackStreamKmsKey
        - PolicyName: LambdaIconikNotificationSQSAccessPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource:
                  - !Ref IconikNotificationSQSQueueArn

  ContentAtomCrossAccountPolicyCODE:
    Type: AWS::IAM::Policy
    Condition: CreateCodeResources
    Properties:
      PolicyName: CrossAccountAccessPolicy
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action:
          - sts:AssumeRole
          Resource:
          - !Ref 'ContentAtomArn'
      Roles:
      - !Ref 'LambdaExecutionRole'

  ContentAtomCrossAccountPolicyPROD:
    Type: AWS::IAM::Policy
    Condition: CreateProdResources
    Properties:
      PolicyName: CrossAccountAccessPolicy
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action:
          - sts:AssumeRole
          Resource:
          - !Ref 'ContentAtomArn'
      Roles:
      - !Ref 'LambdaExecutionRole'

  StatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"

  MediaConvertRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "mediaconvert.amazonaws.com"
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: "S3AccessPolicy"
          PolicyDocument:
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:Get*"
                  - "s3:List*"
                Resource:
                  - !Sub [ "arn:aws:s3:::${Bucket}/*", { "Bucket": !Ref UploadBucketName } ]
              - Effect: "Allow"
                Action:
                  - "s3:Put*"
                Resource:
                  - !Sub [ "arn:aws:s3:::${Bucket}/*", { "Bucket": !Ref DestinationBucketName } ]
  MediaConvertJobTemplate:
    Type: AWS::MediaConvert::JobTemplate
    Properties:
      Description: Media Atom Maker pipeline
      Name: !Sub "media-atom-maker-transcoder-${Stage}"
      SettingsJson:
        TimecodeConfig:
          Source: ZEROBASED
        OutputGroups:
          - Name: MP4
            Outputs:
              - ContainerSettings:
                  Container: MP4
                  Mp4Settings: { }
                VideoDescription:
                  Height: 720
                  Sharpness: 100 # Sharpest possible
                  CodecSettings:
                    Codec: H_264
                    H264Settings:
                      RateControlMode: QVBR # Best quality
                      QualityTuningLevel: MULTI_PASS_HQ # Best quality
                      MaxBitrate: 4800000 # Migrated from Elastic Transcoder
                      QvbrSettings:
                        MaxAverageBitrate: 2400000 # Twice average to give room for encoder's decisions
                        QvbrQualityLevel: 8 # 1-10, 10 is best quality
                        QvbrQualityLevelFineTune: 0.66 # Fine-tuned through manual testing
                      FramerateControl: INITIALIZE_FROM_SOURCE # Follow the source frame rate (default)
                      ParControl: SPECIFIED # Use the pixel aspect ratio specified below
                      ParNumerator: 1 # 1:1 pixel aspect ratio
                      ParDenominator: 1 # 1:1 pixel aspect ratio
                      HrdBufferSize: 10000000 # HrdBufferSize / Bitrate gives a buffer duration of 2-4 seconds; longer duration gives better quality at expense of file size
                      HrdBufferInitialFillPercentage: 90 # Default
                      GopSizeUnits: SECONDS
                      GopSize: 2 # 2 seconds
                      NumberBFramesBetweenReferenceFrames: 1 # 0-15, smaller number gives better quality, higher bitrate and larger file size
                      SceneChangeDetect: DISABLED # Should reduce any interference for videos which loop back to the start
                      CodecProfile: HIGH # Good support for hardware decoding; required by HLS
                      CodecLevel: AUTO # Recommended by HLS, effectively 3.1
                      EntropyEncoding: CABAC # Best quality
                      Slices: 1 # Slices improve encoding speed at the expense of quality - so minimise to 1 slice
                      SaliencyAwareEncoding: PREFERRED # Best quality
                      BandwidthReductionFilter: { } # Having this on reduces detail - so leave it off
                      AdaptiveQuantization: HIGH # Best quality
                      SpatialAdaptiveQuantization: ENABLED # Best quality
                      TemporalAdaptiveQuantization: ENABLED # Best quality
                      FlickerAdaptiveQuantization: ENABLED # Best quality
                AudioDescriptions:
                  - AudioSourceName: Dynamic Audio Selector 1
                    CodecSettings:
                      Codec: AAC
                      AacSettings:
                        Bitrate: 160000
                        CodingMode: CODING_MODE_2_0
                        SampleRate: 44100
              - ContainerSettings:
                  Container: RAW
                VideoDescription:
                  CodecSettings:
                    Codec: FRAME_CAPTURE
                    FrameCaptureSettings:
                      MaxCaptures: 1
                      Quality: 95
            OutputGroupSettings:
              Type: FILE_GROUP_SETTINGS
              FileGroupSettings: { }
          - Name: Apple HLS
            Outputs:
              - ContainerSettings:
                  Container: M3U8
                  M3u8Settings: { }
                NameModifier: "hls"
                VideoDescription:
                  Height: 720
                  VideoPreprocessors:
                    ColorCorrector: # NOTE: only needed for m3u8
                      ColorSpaceConversion: FORCE_709 # Convert to Rec.709 SDR colourspace as per HLS spec pt. 1.24
                  Sharpness: 100 # Sharpest possible
                  CodecSettings:
                    Codec: H_264
                    H264Settings:
                      RateControlMode: QVBR # Best quality
                      QualityTuningLevel: MULTI_PASS_HQ # Best quality
                      MaxBitrate: 4800000 # Migrated from Elastic Transcoder
                      QvbrSettings:
                        MaxAverageBitrate: 2400000 # Twice average to give room for encoder's decisions
                        QvbrQualityLevel: 8 # 1-10, 10 is best quality
                        QvbrQualityLevelFineTune: 0.66 # Fine-tuned through manual testing
                      FramerateControl: INITIALIZE_FROM_SOURCE # Follow the source frame rate (default)
                      ParControl: SPECIFIED # Use the pixel aspect ratio specified below
                      ParNumerator: 1 # 1:1 pixel aspect ratio
                      ParDenominator: 1 # 1:1 pixel aspect ratio
                      HrdBufferSize: 10000000 # HrdBufferSize / Bitrate gives a buffer duration of 2-4 seconds; longer duration gives better quality at expense of file size
                      HrdBufferInitialFillPercentage: 90 # Default
                      GopSizeUnits: SECONDS
                      GopSize: 2 # 2 seconds
                      NumberBFramesBetweenReferenceFrames: 1 # 0-15, smaller number gives better quality, higher bitrate and larger file size
                      SceneChangeDetect: DISABLED # Should reduce any interference for videos which loop back to the start
                      CodecProfile: HIGH # Good support for hardware decoding; required by HLS
                      CodecLevel: AUTO # Recommended by HLS, effectively 3.1
                      EntropyEncoding: CABAC # Best quality
                      Slices: 1 # Slices improve encoding speed at the expense of quality - so minimise to 1 slice
                      SaliencyAwareEncoding: PREFERRED # Best quality
                      BandwidthReductionFilter: { } # Having this on reduces detail - so leave it off
                      AdaptiveQuantization: HIGH # Best quality
                      SpatialAdaptiveQuantization: ENABLED # Best quality
                      TemporalAdaptiveQuantization: ENABLED # Best quality
                      FlickerAdaptiveQuantization: ENABLED # Best quality
                AudioDescriptions:
                  - AudioSourceName: Dynamic Audio Selector 1
                    CodecSettings:
                      Codec: AAC
                      AacSettings:
                        Bitrate: 160000
                        CodingMode: CODING_MODE_2_0
                        SampleRate: 44100
              - ContainerSettings:
                  Container: M3U8
                  M3u8Settings: { }
                NameModifier: "captions"
                CaptionDescriptions:
                  - LanguageCode: ENG
                    CaptionSelectorName: "Caption Selector 1"
                    DestinationSettings:
                      DestinationType: WEBVTT
                      WebvttDestinationSettings: { }
            OutputGroupSettings:
              Type: HLS_GROUP_SETTINGS
              HlsGroupSettings:
                SegmentLength: 10
                MinSegmentLength: 0
        FollowSource: 1
        Inputs:
          - DynamicAudioSelectors: # Only adds audio track if video has audio
              Dynamic Audio Selector 1: { }
            VideoSelector: { }
            TimecodeSource: ZEROBASED
      Tags:
        App: !Ref App
        Stack: !Ref Stack
        Stage: !Ref Stage

  # The following entries are filled in based on the LambdaConfig entries in build.sbt.

  {{GetChunkFromS3}}

  {{UploadChunkToYouTube}}

  {{MultipartCopyChunkInS3}}

  {{CompleteMultipartCopy}}

  {{SendToPluto}}

  {{SendToTranscoderV2}}

  {{GetTranscodingProgressV2}}

  {{AddAssetToAtom}}

  {{AddUploadDataToCache}}

  # Remembers completed uploads since the data is deleted if the pipeline definition is updated
  VideoPipelineCache:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Sub "${App}-cache-${Stage}"
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      Tags:
        - Key: devx-backup-enabled
          Value: true

  VideoPipelinePROD:
    Type: "AWS::StepFunctions::StateMachine"
    Condition: CreateProdResources
    Properties:
      DefinitionString:
        !Sub
          - |-
            {{state_machine}}
          -
            {}
      RoleArn: !GetAtt [ StatesExecutionRole, Arn ]

  VideoPipelineCODE:
    Type: "AWS::StepFunctions::StateMachine"
    Condition: CreateCodeResources
    Properties:
      DefinitionString:
        !Sub
          - |-
            {{state_machine}}
          -
            {}
      RoleArn: !GetAtt [ StatesExecutionRole, Arn ]

  VideoPipelineDEV:
    Type: "AWS::StepFunctions::StateMachine"
    Condition: CreateDevResources
    Properties:
      DefinitionString:
        !Sub
          - |-
            {{state_machine}}
          -
            {}
      RoleArn: !GetAtt [ StatesExecutionRole, Arn ]

  AlertTopic:
    Type: AWS::SNS::Topic
    Condition: CreateProdResources
    Properties:
      DisplayName: !Join ['-', [!Ref 'Stage', Alerts]]
      KmsMasterKeyId: 'alias/aws/sns'
      Subscription:
      - Endpoint: !Ref 'AlertWebhook'
        Protocol: https

  UploadFailedAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: CreateProdResources
    Properties:
      AlarmDescription: Video upload failed
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: '1'
      Namespace: AWS/States
      MetricName: ExecutionsFailed
      Dimensions:
      - Name: StateMachineArn
        Value: !Ref 'VideoPipelinePROD'
      Period: '60'
      EvaluationPeriods: '1'
      Statistic: Maximum
      AlarmActions:
      - !Ref 'AlertTopic'
