{{name}}:
  Type: "AWS::Lambda::Function"
  Properties:
    FunctionName: !Sub "${App}-{{name}}-${Stage}"
    Description: "{{description}}"
    Handler: "com.gu.media.upload.{{name}}::handleRequest"
    Code:
      S3Bucket: !Ref BuildBucket
      S3Key: !Sub
        - "media-service/${Stage}/media-atom-upload-actions/media-atom-uploader.zip"
        - { Stage: !Ref Stage }
    Environment:
      Variables:
        REGION: !Ref AWS::Region
        STACK: !Ref Stack
        APP: !Ref App
        STAGE: !Ref Stage
        CONFIG_BUCKET: !Ref ConfigBucket
        CONFIG_KEY: !Sub
          - "${Stage}/media-atom-maker.private.conf"
          - { Stage: !Ref Stage }
        CREDENTIALS_KEY: !Sub
          - "${Stage}/youtube-service-account.json"
          - { Stage: !Ref Stage }
        ATOM_TABLE_NAME: !Ref 'MediaAtomTable'
        PLUTO_TABLE_NAME: !Ref 'ManualPlutoTable'
        MEDIA_CONVERT_ROLE: !GetAtt MediaConvertRole.Arn
    MemorySize: 512
    Role: !GetAtt LambdaExecutionRole.Arn
    Runtime: "java17"
    Timeout: {{timeout}}
